name: Create Release

on:
  push:
    branches: [ trying-action ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run zip
